### ISSUE TITLE
[BUG] Filter operations don't work when argument contains variables

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#1598]
**Describe the bug**
1. I don't seem to be able to filter for a column name that is set through a field. e.g. `filter: @fields.some_field`

2. An item pipe of the form `filter: @item.some_column == @local.some_local` does not seem to work. See [example_items_pipe_2](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1871410965)

**Use case (for 1)**
The field `workshop_path` can have value `individual` or `together`. Also `individual` and `together` are column names in a data list (with boolean entries). I would like to have a `begin_items` row, with value this data list, and parameter list `filter: @fields.workshop_path`. This does not work.

**Comment by chrismclarke** [comment]
A few notes on this issue mentioned in #1607

**Comment by chrismclarke** [comment]
Trying to unpick this issue (and more a note to self).

The main problem is the way that the filter operation that only appears as a single row entry needs to be applied to every row generated after applying the template to the item list.

This means that the dynamic context is evaluated in 2 separate actions, step 1 is the template evaluator which handles `@local`, `@field` etc. The nature of the template evaluator means that the partial evaluation replaces as an unquoted string (normally to be rendered), i.e.

`@item.first_name=== @local.other_field` -> ` @item.some_field === some_value`

When it comes time to evaluate the item which is done using a separate evaluation system, the `appStringEvaluator` performs more string replacement, which doesn't help to evaluate the expression.
`@item.first_name=== some_value` -> ` Ada=== some_value`

The possible workaround could be:
1. Add a workaround to force template evaluator to retain quoted strings `@item.some_field === "some_value"` and update the `AppStringEvaluator` to do similar before evaluating ` "Ada"=== "some_value"` -> `false`

2. Bypass the template evaluator to avoid partial string substitution and use a different system to evaluate as a single expression with full context value `@item.first_name=== @local.other_field` , `{item:first_name:'Ada', local:other_field:'some_value'}`
