### ISSUE TITLE
[FEATURE] Landscape mode

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2114]
**What?**
Ability to show particular templates in landscape mode

**Why?**
The PLH Kids deployment wants to [display "storybooks"](https://github.com/IDEMSInternational/plh-kids-app-content/issues/15) in landscape mode, so that a 1:2 ratio landscape image can be displayed as big as possible. The rest of the app needs to still be used in portrait mode.

<img width="336" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/02826952-ed2f-4dc1-9503-4491c514bd94">

**Comment by jfmcquade** [comment]
According the [Capacitor docs](https://capacitorjs.com/docs/guides/screen-orientation#dynamic-orientation-settings), we should be able to handle this using the [cordova-plugin-screen-orientation](https://www.npmjs.com/package/cordova-plugin-screen-orientation) plugin.

**Comment by chrismclarke** [comment]
Recommend main layout should be flex box to support portrait/landscape orientation
Contents list should provide template parameter_list option for `screen_orientation` with values for landscape (default portrait)
Template navigation should likely watch for this parameter and pass into url as a query parameter, e.g. `/template/my_template?screen_orientation=landscape (portrait would be undefined/null and shoudl remove parameter)
Will need some screen-orientation service that listens to router and calls api as required
