### ISSUE TITLE
[FEATURE] toggle bar component: migrate to use modern ion-toggle sytnax

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/open-app-builder#2212]
**What?**
The `toggle_bar` component makes use of the `ion-toggle` component, adding custom styling. This styling makes use of a syntax that ionic now considers to be [legacy](https://ionicframework.com/docs/api/toggle#using-the-legacy-syntax). We should update to use the new "[modern syntax](https://ionicframework.com/docs/api/toggle#using-the-modern-syntax)".

**Why?**
This legacy syntax will be deprecated in an upcoming major release of ionic.

**How?**
Migrating the basic styling should be reasonably straightforward, but accounting for our custom icons, enabled via the `show_tick_and_cross` parameter, is likely to be a bit more involved. We should consider replacing our custom on/off labels with a feature introduced for `ion-toggle`, accessed via a new [enableOnOffLabels](https://ionicframework.com/docs/api/toggle#on--off-labels) property. It appears these icons can't be customised: there is only one option for Android and one option for iOS, so we should decide whether it would be acceptable to use these instead of our custom implementation.
Native ionic on/off labels (from [here](https://ionicframework.com/docs/api/toggle#on--off-labels)):
<img width="217" alt="Screenshot 2024-02-23 at 14 08 49" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/785f57fd-e9a4-4f29-9ea1-e4195b001467">
<img width="215" alt="Screenshot 2024-02-23 at 14 08 54" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/2fa605bb-8b51-48fe-af14-5144359a8540">
<img width="234" alt="Screenshot 2024-02-23 at 14 08 59" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/35591740-5cdd-438b-9887-3ecffbd217b3">
<img width="229" alt="Screenshot 2024-02-23 at 14 09 04" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/6bc7c151-483a-4515-ae5a-394ed0791055">

**Comment by jfmcquade** [comment]
The legacy syntax is [deprecated in Ionic 8](https://ionicframework.com/docs/v8/updating/8-0#toggle).

**Comment by kwAsant** [comment]
These are the results I have got: 
<img width="355" alt="image" src="https://github.com/IDEMSInternational/open-app-builder/assets/88288104/5335f293-8d84-48c4-94e5-ebc45858911d">

<img width="357" alt="image" src="https://github.com/IDEMSInternational/open-app-builder/assets/88288104/e37f204a-d4b5-40f5-b97f-e60f6f248da1">

It seems that there is no way to have tick and cross appear on the modern syntax, it seems.

I have also migrated it following the instructions specified here: https://ionicframework.com/docs/api/toggle#using-the-modern-syntax

**Comment by jfmcquade** [comment]
@kwAsant I think that's probably broadly acceptable, I don't think it's necessarily a problem that the toggle bar doesn't look exactly the same as before. We can discuss with @esmeetewinkel tomorrow. 

I would say there are a couple of visual differences between the toggle bars in your screenshots and those of the native ionic components: in your screenshots, the "track" of the slider is visible either side of the circular slider element, whereas in ionic's examples, the circular slider goes right to the edge of the track. Also, the examples in the ionic docs show a `-` and `tick` icon depending on the value of the toggle, whereas in your screenshots only the `-` symbol displays. Have you figured out if these differences are due to custom styling we're applying? I think we'd like to expose the option of displaying the icons and have this able to be authored using the existing "show tick and cross" parameter.

**Comment by kwAsant** [comment]
Oh that's cool (I read this but forgot to reply). Will make a pull request.

**Comment by kwAsant** [comment]
Using these two links, I found out that we can alternate between an "ios" mode and an "md" mode. I have switched the `mode` to 'ios': https://ionicframework.com/docs/api/toggle#basic-usage. This was where I found the property: https://ionicframework.com/docs/api/toggle#properties. This fixed the issue of the toggle not being long enough: 
<img width="368" alt="image" src="https://github.com/user-attachments/assets/81ec691a-e610-4caa-87c2-dec900f8d741">

Will make a PR now however
