### ISSUE TITLE
[FEATURE] New task "journey" design

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2324]
**What?**
Display component that displays a list of tasks (which may themselves be task groups) as a route connecting dots. 

![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/93348eb3-ac6d-49ea-9614-6d8b306d5038)

<img width="234" alt="Screenshot 2024-08-19 at 15 09 10" src="https://github.com/user-attachments/assets/603b42a0-b053-4e74-9fce-1a6289337ec0">

**Why?**
This design would evoke the feeling of being on a learning journey. Inspired by other learning app designs.

**How?**
- Screen divided into two columns, design needs to scale sensibly also when long text strings are provided as titles
- Each task can have different statuses which will have minor effects on the way it is displayed (such as completed, locked)

**Comment by ChrisMarsh82** [comment]
https://www.figma.com/design/hUwQvxkWDYKRJltebSayYN/ParentApp-for-Kids
