### ISSUE TITLE
[BUG] Data items: error trying to modify final fields

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/open-app-builder#2327]
Extracted from the PR description of #2325:

> I'm not sure if related to this PR or not but starting to see issue with modifying final fields
> ![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/10515065/ae67326f-99cd-4347-9e72-cbb943117665)
> 
> (update - seeing on main - possibly may want to address after merge #2323)

I'm unable to replicate this (using [comp_data_items](https://docs.google.com/spreadsheets/d/1khGTrDekzqDQyW1r2x0ADqknanrlkmhOz1RRzhP6-7c/edit#gid=845703892)) on `master` or the feature branch for #2325, @chrismclarke could you provide some more details?

This is very likely to be an issue introduced by #2312, and looking at the error in your screenshot I think the problem is to do with the `row_index` property (the only `final` property in the schemas for the `persistedMemory` and `reactiveMemory` adapters) and where that property is being saved: either at the top level of the doc or inside the `data` property. Potentially this is a new issue introduced by #2325 (which persists on master when data overwrites have been made on that feature branch), but probably unlikely.

**Comment by chrismclarke** [comment]
OK, if not replicated when working locally I'd say probably safe to close for now - could be linked to a previous local dev state. Also as these issues are not tracked in production can just reopen if replicated in the future
