### ISSUE TITLE
[FEATURE] Map component

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/open-app-builder#2358]
**What?**
A component for displaying interactive maps, with various options to display layers of data.

**Why?**
A research group are looking to build a web app to display some data relating to predicting conflicts. The group's aim is to improve conflict prediction, helping forecasters and decision makers. The purpose of app is to provide easier access to their information and data.

INNODEMS are handling the app authoring, see [this content repo](https://github.com/IDEMSInternational/conflict-forecast-content). An integral part of the proposed app is an interactive map, that will display various layers of data. This will require a new map component.

Whilst a map component would be a welcome addition to the app builder, there are currently no other use cases. Along with the fact that the group would like a version of the app very soon (potentially containing a placeholder for the map element), and the fact that dev work on this does not seem to come under any existing contract, it would seem sensible to build a new map component that is designed to meet the immediate needs, without necessarily offering full flexibility. The usual attempts should be made to generalise the component and its API as much as possible, but in this case it need only be minimally generalised.

Potential examples can be found [here](https://conflictforecast.org/) and [here](https://ucdp.uu.se/).

**How?**
In the spirit of "open by default", an open source mapping package should be considered first. Prime candidates would be:
- [OpenLayers](https://openlayers.org/)
- [Leaflet](https://leafletjs.com/)

A comparison of the two libraries can be found [here](https://www.geoapify.com/leaflet-vs-openlayers/). I would lean towards using OpenLayers, which seems to offer greater functionality (potentially with a greater learning curve).

**Other details**
The mapping package is likely to be pretty heavy, and therefore it should ideally be an opt-in feature to avoid adding too much to our app bundle size by default. We do not currently have the ability to opt-in to specific features and have them removed from the build by default, and so it may be that for the time being it makes sense to manage this via a dedicated branch on the code repo that contains the map component code.
This issue does provide motivation for increasing the priority of disabling features in an opt-in way, see #2108 and #2265

**Comment by chrismclarke** [comment]
@jfmcquade - any idea why this didn't auto-close with #2361? Maybe a git issue (unless you updated the description after merging?)

**Comment by jfmcquade** [comment]
> @jfmcquade - any idea why this didn't auto-close with #2361? Maybe a git issue (unless you updated the description after merging?)

Hmm no, strange. I'm pretty sure I didn't update the description after merging. Potentially something to do with changing the target branch for #2361 (which I did a few times)?
