### ISSUE TITLE
[FEATURE] Ability to define PII data

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/open-app-builder#2444]
**What?**
The ability for content authors to be able to flag when data that is to be collected and stored in the database is personally identifiable information. Thus allowing data in the database to be split between PII and non-PII, making sure we and all our users can adhere to GPI

**Why?**
Making sure data privacy can be handled by content authors and automatic mechanisms can be put in place to comply with GPI regulations automatically

**How?**
The initial step should be a flag that can be added to the templates. Further steps can be added to the database once we fully understand the type of data collected and ways that we can separate this from non-PII data.

**Comment by esmeetewinkel** [comment]
@chrismclarke will work on an RFC

**Comment by chrismclarke** [comment]
RFC created
https://docs.google.com/document/d/1i3OQRz3FwdwrOahGWE6rAWGQ2twhN8gWy8LxPzzUT1I/edit

**Comment by chrismclarke** [comment]
Closing here to move into RFC tracking issue #2516
