### ISSUE TITLE
[FEATURE] Ability to add new rows to a dynamic data list

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2476]
**What?**
Need an action to add a new row to a dynamic data list, setting its ID and properties. 

**Why?**
For the [FacilitatorApp multiple parent groups feature](https://github.com/ParentingForLifelongHealth/plh-facilitator-app-content/issues/68) we need to refactor the existing authoring of managing groups of parents. Currently we're storing parents in a nested json object, rather than a dynamic data list. It would make sense to store the list of parents as a dynamic data list, however, it is not predetermined how long this list will be.

**Comment by chrismclarke** [comment]
Closed with #2625
