### ISSUE TITLE
Parser to substitute `\r` by `\n`

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2499]
**Past discussion**
> Agreed, `\r` doesn't exist in the wild without `\n` (see my [comment](https://github.com/IDEMSInternational/parenting-app-ui/issues/1838#issuecomment-1469751567) on the linked issue), so just need the single replacement

_Originally posted by @chrismclarke in https://github.com/IDEMSInternational/open-app-builder/pull/1844#discussion_r1136845795_

**Current issue**
I now did come across some cases of `\r` existing in the wild without `\n`, see [Crowdin](https://idems.crowdin.com/editor/3/519/en-ar/17?view=comfortable&filter=basic&value=0#q=%5Cr) (PLH Kids KW deployment)
![image](https://github.com/user-attachments/assets/2384d068-b3f2-4663-affe-dd36ca4aa4c0) 

Could we re-insert the feature in the parser that replaces `\r` by `\n`? See discussion on linked PR comment thread https://github.com/IDEMSInternational/open-app-builder/pull/1844#discussion_r1136845795

**Comment by chrismclarke** [comment]
Do we know how/where these have originated from. I'd be keen to know a bit more about the source so that I can have a better idea of where best we need to apply a fix. Does this appear in the sheets before they get extracted for crowdin?

**Comment by esmeetewinkel** [comment]
> Do we know how/where these have originated from. I'd be keen to know a bit more about the source so that I can have a better idea of where best we need to apply a fix. Does this appear in the sheets before they get extracted for crowdin?

Yes, indeed, this appears in the app content jsons before they get extracted for Crowdin, for example [childdevelopment_articles.json](https://github.com/ParentingForLifelongHealth/plh-kids-app-kw-content/blob/main/app_data/sheets/data_list/modules/childdevelopment_articles.json). They are not visible in the [corresponding Google sheet](https://docs.google.com/spreadsheets/d/1xSPd9go3Bi9LwsFMKD4C6kdpVeHm3tVhcIxUlaKrpgQ/edit?gid=2065367350#gid=2065367350) nor in the [corresponding sidekick-linked Google doc](https://docs.google.com/document/d/1wUVFb8x-bFKkith4JeGM5zFS82qpNuHvmcSe1loSUwI/edit?tab=t.0) but I do believe they originate from there.

**Comment by chrismclarke** [comment]
Ah, ok. If I had to guess in that case I imagine it previously wasn't possible to add `\r\n` style replacements from within a google sheet, but now maybe is possible from sidekick (or other sources via copy-paste perhaps). Should be fairly straight-forward to fix, I'll draft a quick PR to test
