### ISSUE TITLE
[BUG] [isEqual] could not compare two strings

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2528]
**Describe the bug**
 Getting a warning `[isEqual] could not compare option_1 option_2` when selecting two different string options in a combo box. 

**App version**
v0.17.0

**To Reproduce**
Navigate to https://plh-kids-tz.web.app/template/article_play_the_power_of_play_16, select something in the combo box and then select something else. 

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/2c9f26d3-592a-444f-adfb-c686b83fd148)

**Additional context**
This warning seems to have been added in PR https://github.com/IDEMSInternational/open-app-builder/pull/2484

**Comment by chrismclarke** [comment]
This is a false-positive in the logging, it will be removed in #2513
