### ISSUE TITLE
[FEATURE] Kuwait Theme - Completion Modal

### ISSUE THREAD

**Issue by FaithDaka** [IDEMSInternational/open-app-builder#2540]
**What?**
Create a module completion component according to the Kuwait theme design.

**Why?**
This modal congratulates a user after they have completed a module and links to a moment of play activity.

**How?**
- [x] Create a module completion component. This component activates after a user clicks the trophy icon and completes the module.
- [x] Declare it within the `index.ts` file within the plh folder
- [x] Create a component sheet with the desired attributes
- [x] Test the component with data from the component sheet

**Other details**
<img width="200" src="https://github.com/user-attachments/assets/c523e3a6-82c5-4974-8865-f0914db17b9b">

**Comment by jfmcquade** [comment]
Thanks, @esmeetewinkel, I've replied inline on the linked PR [here](https://github.com/IDEMSInternational/open-app-builder/pull/2601#pullrequestreview-2481302301).
