### ISSUE TITLE
[FEATURE] Kuwait Theme - Activity Library components

### ISSUE THREAD

**Issue by FaithDaka** [IDEMSInternational/open-app-builder#2541]
**What?**
The activity library holds the activities to be used by the parents. Activities get unlocked according to the modules completed and can be filtered by age group or activity state(unlocked, favourite). It also includes a streak count of the number of videos unlocked.

**Why?**
The library provides easy accessibility to the activities for parents.

**How?**
- [x] Activity card component
- [ ] Streak count component
- [ ] Filter component
- [x] Category filter component

**Other details**
<img width="250" src="https://github.com/user-attachments/assets/7a49911f-8627-459a-9e89-84d77db3875d">

**Comment by esmeetewinkel** [comment]
@FaithDaka in case it's helpful: I've now authored a placeholder page for this: `activity_library` [template](https://docs.google.com/spreadsheets/d/1V8iYNvVVc0whiZ3p--ulL_93DiOEH_SKwwwSqLX6OE4/edit?gid=0#gid=0) and [preview](https://plh-kids-kw-uat1.web.app/template/activity_library)

![image](https://github.com/user-attachments/assets/0024f299-b1e7-4a42-a314-5649ef16238a)
