### ISSUE TITLE
[BUG] plh_module_list_item not displaying

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2554]
**Describe the bug**
The component `plh_module_list_item` is no longer displaying (it did when testing PR #2527). I can't see any relevant logs in the console, so I'm a bit at a loss...

**App version**
v0.17.0 

**To Reproduce**
Navigate to https://idems-debug.web.app/template/comp_plh_module_list_item

**Debug Sheet(s)**
[comp_module_list_item](https://docs.google.com/spreadsheets/d/1Tq8Ib_ZcJsABW9U9XbQxgnmtv_uayXk28DXoa94j1aE/edit?gid=569531329#gid=569531329)

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/3b9ce804-5781-4844-82ad-58744c6132b3)

**Comment by jfmcquade** [comment]
This should be resolved by #2551
