### ISSUE TITLE
[FEATURE] icon only button

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/open-app-builder#2572]
**What?**
Ability to add a button that has no border and is just an icon
![image](https://github.com/user-attachments/assets/b14929c1-26e4-4dd9-9624-e06689ffa4fa)
![image](https://github.com/user-attachments/assets/b1c898ab-2371-4eea-85dd-78391fcbf571)
![image](https://github.com/user-attachments/assets/23d0ad4e-8f72-475c-b0a1-8b04fe586d0d)

**Why?**
Needed for Facilitator MX deployment

**How?**
Could this be done using a round button? Currently, we can add a round_button with an icon. Can this be amended to be the same colour as the background?

**Comment by jfmcquade** [comment]
@FaithDaka This should be achievable using the current round button component. I would suggest adding a new variant, `no-background`, that makes the circle container transparent (and probably makes the icon appear slightly larger)

**Comment by FaithDaka** [comment]
@jfmcquade I can add that to this PR: https://github.com/IDEMSInternational/open-app-builder/pull/2585
