### ISSUE TITLE
[BUG] Text in congratulations pop-up not taking on theme

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/open-app-builder#2649]
**Describe the bug**
When you navigate to a module completion page, the sub-title text appears black, rather than the themed navy blue

**To Reproduce**
Complete a module, select the trophy and open the page reading "Hurrah"

**Screenshots and videos**
![Screenshot_20241220-144309](https://github.com/user-attachments/assets/ee63cc3e-9a7c-4c1c-87d8-597bead74956)

**Comment by esmeetewinkel** [comment]
Thanks @lauriemarkle, resolved now by content repo PR https://github.com/ParentingForLifelongHealth/plh-kids-app-kw-content/pull/105

In future could you post issues on the content repo? That way I can triage them between authoring fixes I can make myself and issues that need developer input.
